#- type: entity
#  name: telescopic baton
#  parent: BaseItem
#  id: TelescopicBaton
#  description: A telescopic baton for incapacitating people with.
#  components:
#  - type: Sprite
#    sprite: Debiloid1984/Objects/Weapons/Melee/telescopic.rsi
#    netsync: false
#    layers:
#    - state: telescopic_off
#      map: [ "enum.ToggleVisuals.Layer" ]
#  - type: Stunbaton
#    energyPerUse: 100
#  - type: UseDelay
#    delay: 0.75
#  - type: MeleeWeapon
#    damage:
#      types:
#        Blunt: 5
#    bluntStaminaDamageFactor: 2.0
#    angle: 60
#    animation: WeaponArcSlash
#  - type: StaminaDamageOnHit
#    damage: 35
#  - type: Battery
#    maxCharge: 5000
#    startingCharge: 5000
#  - type: ItemCooldown
#  - type: Item
#    heldPrefix: off
#    size: Small
#  - type: Clothing
#    sprite: Debiloid1984/Objects/Weapons/Melee/telescopic.rsi
#    quickEquip: false
#    slots:
#      - Belt
#  - type: DisarmMalus
#    malus: 0.225
#  - type: Appearance
#  - type: GenericVisualizer
#    visuals:
#      enum.ToggleVisuals.Toggled:
#        enum.ToggleVisuals.Layer:
#          True: {state: telescopic_on}
#          False: {state: telescopic_off}
#  - type: StaticPrice
#    price: 100
