- type: playTimeTracker
  id: JobCommanderSalvage

- type: playTimeTracker
  id: JobBlueShield

- type: playTimeTracker
  id: JobMiner

- type: playTimeTracker
  id: JobSeniorEngineer

- type: playTimeTracker
  id: JobSeniorOfficer

- type: playTimeTracker
  id: JobSeniorPhysician

- type: playTimeTracker
  id: JobSeniorResearcher

- type: playTimeTracker
  id: JobCentComConsultant