- type: job
  id: BlueShield
  name: job-name-blueshield
  description: job-description-blueshield
  playTimeTracker: JobBlueShield
  requirements:
    - !type:RoleTimeRequirement
      role: JobCaptain
      time: 54000 #15 hrs
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 36000 #10 hrs
    - !type:RoleTimeRequirement
      role: JobChiefMedicalOfficer
      time: 18000 #5 hrs
  weight: 20
  startingGear: BlueShieldGear
  icon: "JobIconBlueShield"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Captain
  - Command
  - Medical
  - Engineering
  - External
  - Security
  - Brig
  - Maintenance
  - Cargo
  - Research
  #start-backmen: currency
  minBankBalance: 400
  maxBankBalance: 600
  wageDepartment: Command
  wage: 100
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
      - type: PsionicBonusChance
        flatBonus: 0.025
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: BlueShieldGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBlueShield
    back: ClothingBackpackBlueShieldFilled
    shoes: ClothingShoesBootsSpetsnazFilled
    eyes: ClothingEyesGlassesSunglassesBlueShield
    gloves: ClothingHandsGlovesCombat
    head: ClothingHeadHatBlueShieldBeret
    outerClothing: ClothingOuterArmorBlueshield
    id: BlueShieldPDA
    ears: ClothingHeadsetAltBlueShield
    pocket1: HandheldCrewMonitor
    pocket2: WeaponPistolG22
  innerClothingSkirt: ClothingUniformJumpskirtBlueshield
  satchel: ClothingBackpackSatchelBlueShieldFilled
  duffelbag: ClothingBackpackDuffelBlueShieldFilled
