- type: latheRecipe
  id: MagazineBoxUniversalPT1
  result: MagazineBoxUniversalPT1
  completetime: 5
  materials:
    Steel: 1800

- type: latheRecipe
  id: MagazineBoxUniversalVPS
  result: MagazineBoxUniversalVPS
  completetime: 5
  materials:
    Steel: 3200

- type: latheRecipe
  id: MagazineShotgunSaiga
  result: MagazineShotgunSaiga
  completetime: 5
  materials:
    Steel: 200

- type: latheRecipe
  id: MagazineUniversalShortHv
  result: MagazineUniversalShortHv
  completetime: 5
  materials:
    Steel: 575

- type: latheRecipe
  id: MagazineUniversal
  result: MagazineUniversal
  completetime: 5
  materials:
    Steel: 430

- type: latheRecipe
  id: SpeedLoaderUniversal
  result: SpeedLoaderUniversal
  completetime: 5
  materials:
    Steel: 200

- type: latheRecipe
  id: MagazineMagnumSubMachineGun
  result: MagazineMagnumSubMachineGun
  completetime: 5
  materials:
    Steel: 450

- type: latheRecipe
  id: MagazineLightMachineGunDrum
  result: MagazineLightMachineGunDrum
  completetime: 5
  materials:
    Steel: 500
